import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import ThemeProvider from "@/providers/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gerenciador de backup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider  >
    <html lang="pt-br" suppressHydrationWarning >
      <body
        className={   `${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
              defaultTheme="light" attribute="class" enableSystem
          >

            {children}
          </ThemeProvider>
      
      </body>
    </html>
    </AuthProvider>
  );
}
