
export type clientsRequest = {
     codigo: number,
     codMatriz: number,
     diasUso: number,
     qtdeFiliais: number,
     qtdeTerminais: number,
     portaTs: number,
     portaSsh: number,
     atendente: string,
     contrato: string,
     acesso: "L" | "B" | "A" ,
     dataLiberacao: string,
     dataAcesso: string,
    razaoSocial:string,
    nomeFantasia:string,
    nomeReduz:string,
    ip:string,
    cnpj:string,
    inscricao:string,
    cep:string,
    endereco:string,
    numero:string,
    complemento:string,
    bairro:string,
    cidade:string,
    estado:string,
    email:string,
    telefone:string,
    fax:string,
    sistema:string,
    empresa:string,
    host:string,
    usuarioTs:string,
    senhaTs:string,
    senhaRootTs:string,
    usuarioSsh:string,
    senhaSsh:string,
       efetuar_backup: 'S' | 'N' ,
       portaVnc: number,
       portaMysql: number | string,
       idTeamviewer:number,
       versaoFinanceiro: number,
       versaoVendas: number,
       versaoContabil: number,
       versaoPcp: number,
       versaoShopping: number,
       versaoTelevendas: number,
       contato: null | string,
       hora_agenda_backup: null | string, 
       tipoVersao: null | string,
       nomeCertificado: null | string ,
       senhaCertificado: null | string,
        senhaRootSsh: string | null,
        senhaVnc: string | null,
        usuarioMysql: string | null,
        senhaMysql: string | null,
        senhaRootMysql: string | null,
        senhaTeamviewer: string | null,
        emailCont: string | null,
        dataCadastro: string | null,
        nomeRadmin: string | null,
        senhaRadmin: string | null,
        nomeBanco: string | null,
        ativo: string | null,
        caminhoBkp: string | null,
        observacao: string | null,
        dataModificacao: string | null,
        arquivoMaisRecente: string | null,
        dataAtualizacao: string | null,
        latitude: string | null,
        longitude: string | null,
        atualizar: string | null,
        data_ultimo_backup: string | null,
        bancos_backup: string | null,
        status_backup: 'finalizado' | 'em-andamento' | 'erro' | 'pendente' | null ,
        msg_backup: string | null,

}
 